### ISSUE TITLE
Create full html page like txt but with working links.

### ISSUE THREAD

**Issue by famewolf** [onyxbits/listmyaps#1]
Can the program be made to product a full "myapps.html" webpage which can be viewed locally or shared?  Currently it just provided me some garbled links...and the text mode while detailed doesn't provide links to google play etc.  

You perhaps could also consider checking the google play links for a bad return code and removing the one's that are not valid when it's turned on for all apps.

Thanks for your app.  I find it very useful to pass info along to other of apps I recommend.

**Comment by onyxbits** [comment]
Am Dienstag, den 17.09.2013, 04:50 -0700 schrieb famewolf:

> Can the program be made to product a full "myapps.html" webpage which
> can be viewed locally or shared? Currently it just provided me some
> garbled links...and the text mode while detailed doesn't provide links
> to google play etc. 

That seems to be a popular request, to which my answer always is: what
would this myapps.html look like? Some people might prefer a very plain
html page, others might want CSS in there, yet others would require
headers and footers. There is simply no way to provide a "one size fits
all" solution that is also easy to use.

The idea here really is that LMA provides the "proto output" that you
can copy&paste/share to some other piece of software (e.g. the comment
form of a blog) that knows how to embed the markup in a template that
will result in "myapps.html".

> You perhaps could also consider checking the google play links for a
> bad return code and removing the one's that are not valid when it's
> turned on for all apps.

I would rather not want to do that for a couple of reasons:
- It requires network access permission. Many people (including myself)
  have privacy concerns when an app wants to talk to the rest of the
  world.
- Checking for a couple dozen apps via http takes a bit of time,
  produces a fair bit of data and might be seen as "phoning home". A lot
  of people don't appreciate that.
- UI wise this will end in a bit of a nightmare. Putting a "check if on
  Google Play" entry is simple, but you also have to somehow communicate
  the result back to the user. Simply unchecking apps is not really an
  option.

> Thanks for your app. I find it very useful to pass info along to other
> of apps I recommend.

Glad you like it :).

**Comment by famewolf** [comment]
I don't see how a barebones wrapper around the output would be complicated..just enough for local viewing and following your own links...an option could be put into settings to enable the wrapper or not...if you made a header.html and a footer.html and just referenced them people could edit them however they wanted without it affecting your program.   

If I want to share my apps with friends via gmail there is currently no good way to do so..if I give them the text there are no links..if I paste in the html  gmail doesn't process it as a blog post might.

**Comment by onyxbits** [comment]
Am Donnerstag, den 19.09.2013, 18:15 -0700 schrieb famewolf:

> I don't see how a barebones wrapper around the output would be
> complicated..just enough for local viewing and following your own
> links...an option could be put into settings to enable the wrapper or
> not...if you made a header.html and a footer.html and just referenced
> them people could edit them however they wanted without it affecting
> your program. 
> 
> —
> Reply to this email directly or view it on GitHub.

That template feature is surprisingly labor intensive to implement (at
least when you want to do it right). I just pushed a not quite final
version to github. Have a look, play around, tell me if you manage to
crash it or get wrong results.

**Comment by famewolf** [comment]
Thanks.  I compiled it and will give it a test although your project seems to be missing the libs folder with android-support-v4.jar in it.  Could be something I did wrong as I'm new to git and ant.

**Comment by onyxbits** [comment]
Am Dienstag, den 24.09.2013, 17:27 -0700 schrieb famewolf:

> Thanks. I compiled it and will give it a test although your project
> seems to be missing the libs folder with android-support-v4.jar in it.
> Could be something I did wrong as I'm new to git and ant.
> 
> —
> Reply to this email directly or view it on GitHub.

Nope, you have to add that lib yourself. I don't check in library
dependencies.

**Comment by Valeryan24** [comment]
Hello,
This "List my Apps" application is very useful, and fact of being opensource + available on F-Droid repository is very great.
Regarding the need to get a full html page with links that could be opened in a browser, this is very easy IMHO :
When we select Copy/Share as HTML list, just change only the extension to "html" instead of "txt", it will register the file correctly and works then.
Ex on the screenshot, I just modified on my file manager extension to html then opened in Firefox :
![listmyapps](https://f.cloud.github.com/assets/1119619/1876010/46a4ee8e-7907-11e3-8e4b-b0e7089a4719.png)
On the top, the txt file as saved by "List My Apps", on the bottom, the same file saved with html extension, it is well enough, name and link of the app, no need of something else, but much more usable and nice !
Thanks in advance :)

**Comment by onyxbits** [comment]
Am Donnerstag, den 09.01.2014, 00:26 -0800 schrieb Valeryan24:

> Hello,
> This "List my Apps" application is very useful, and fact of being
> opensource + available on F-Droid repository is very great.
> Regarding the need to get a full html page with links that could be
> opened in a browser, this is very easy IMHO :
> When we select Copy/Share as HTML list, just change only the extension
> to "html" instead of "txt", it will register the file correctly and
> works then.
> Ex on the screenshot, I just modified on my file manager extension to
> html then opened in Firefox :
> listmyapps
> On the top, the txt file as saved by "List My Apps", on the bottom,
> the same file saved with html extension, it is well enough, name and
> link of the app, no need of something else, but much more usable and
> nice !
> Thanks in advance :)
> 
> —
> Reply to this email directly or view it on GitHub.

Only problem: LMA sports a template editor and is therefore agnostic to
what type of text you are sharing. Since LMA has no way of telling what
the template is suppose to generate, it can only share it as the general
supertype which is ".txt".
