### ISSUE TITLE
How to help with French translation ?

### ISSUE THREAD

**Issue by Valeryan24** [onyxbits/listmyaps#3]
Last thread for today :)
I'd like to help translating into french, but have no idea which file or source I should edit to give you the correct words, please could you advise ?
Thanks again.

**Comment by onyxbits** [comment]
Am Donnerstag, den 09.01.2014, 00:44 -0800 schrieb Valeryan24:

> Last thread for today :)
> I'd like to help translating into french, but have no idea which file
> or source I should edit to give you the correct words, please could
> you advise ?
> Thanks again.
> 
> —
> Reply to this email directly or view it on GitHub.

Sure thing:
- clone my repository
- create a directory res/values-fr
- copy res/values/strings.xml to it
- translate away, make a testbuild, if everything works, send me a pull
  request.
