### ISSUE TITLE
Misc. UI Improvements

### ISSUE THREAD

**Issue by ghost** [onyxbits/listmyaps#4]
I feel that the UI, while good overall, could use a little neatening up and perhaps some polish.
- Could the "Copy/Share as" selection be moved to when the user needs it? E.g. have it appear at the top of the selection dialog? The idea here is to de-clutter the main screen. (Maybe this option would also better suit a settings menu but research may have to be done on how often users actually change this option.)
- "Always link to Google Play" seems that it would be better suited to a settings menu. Again, this would help de-clutter the main screen.
- The bottom of the apps list doesn't align with the bottom of the screen and breaks the overall feel of the ListView.
- Find a more appropriate icon for the "Browse" Action Bar item. The two arrows would currently seem to signify "upload and download", which to an extent is accurate, but gives the user fairly mixed messages. Are you browsing, are you uploading/downloading or are you submitting data?
- Reduce Action Bar items to showing icons only, adhering to the "long-press hint" pattern just in case the user isn't sure about what each item does. This would require finding a more appropriate "Browse" icon, as mentioned above.
- Template editing is pretty cumbersome. Who likes typing $, { or } on a phone keyboard? Maybe add some buttons to the editor for common actions, e.g. "Insert app title", "Insert comment", etc. Perhaps even utilise a dropdown menu?
- Add a "preview" button to the template editor so that users can see a demonstration of what their template will look like. Perhaps with sample data randomly selected from the user's installed apps?
- Remove redundant "You can have as many as you like" text from the template editor. Users will not assume that there are any limits to the number of templates.
- The "No apps tagged!" text may be better suited to a toast notification?

I'd be interested to hear responses to any of the points above. I'm fully prepared to submit code for some/all of these points but I'd like to hear some feedback first and discuss how to progress.

Regards,
- Michael.

**Comment by onyxbits** [comment]
Hi,
wow, large list of suggestions.

Am Freitag, den 28.03.2014, 14:03 -0700 schrieb Michael Stubbs:

> I feel that the UI, while good overall, could use a little neatening
> up and perhaps some polish.
> 
> ```
>   * Could the "Copy/Share as" selection be moved to when the user
>     needs it? E.g. have it appear at the top of the selection
>     dialog? The idea here is to de-clutter the main screen. (Maybe
>     this option would also better suit a settings menu but
>     research may have to be done on how often users actually
>     change this option.)
> ```

I tried to avoid having a settings screen for a number of reasons:
a) I made a stupid design choice in the beginning: making the screens
activity and not fragment based. That means whenever you change screens,
you are changing activities and that means LMA rescans the device. I
guess it would be pretty annoying for the user to wait for a rescan
whenever s/he changes a setting.

b) Google kinda discourages the use of a settings screen and I agree
with that.

c) I actually change the output format quite often, so going to a
settings screen would be rather uncompfortable (there are a number of
users who got self-defined templates for "internal use" in addition to
the default "share me" templates).

d) I want that little bit of clutter on top of the list. I think it
makes the app look less boring.

> ```
>   * "Always link to Google Play" seems that it would be better
>     suited to a settings menu. Again, this would help de-clutter
>     the main screen.
> ```

I would agree, but a settings screen with just one item looks terribly
unbalanced.

> ```
>   * The bottom of the apps list doesn't align with the bottom of
>     the screen and breaks the overall feel of the ListView.
> ```

Not quite sure what you mean? The 5dp border around the screen? That's a
Google recommendation.

> ```
>   * Find a more appropriate icon for the "Browse" Action Bar item.
>     The two arrows would currently seem to signify "upload and
>     download", which to an extent is accurate, but gives the user
>     fairly mixed messages. Are you browsing, are you
>     uploading/downloading or are you submitting data?
> ```

Unfortunately, the iconset that comes with the Android SDK is rather
limited. That one was the best match and it at least makes the user
aware that s/he is about to do network IO. I can't really think of
anything that would properly symbolize what the button does. 

> ```
>   * Reduce Action Bar items to showing icons only, adhering to the
>     "long-press hint" pattern just in case the user isn't sure
>     about what each item does. This would require finding a more
>     appropriate "Browse" icon, as mentioned above.
> ```

Hm. I'm not sure if people actually know the "long press hint" pattern.
I don't nescessarily object to changing that, but as you said: the
problem is the "browse" button.

> ```
>   * Template editing is pretty cumbersome. Who likes typing $,
>     { or } on a phone keyboard? Maybe add some buttons to the
>     editor for common actions, e.g. "Insert app title", "Insert
>     comment", etc. Perhaps even utilise a dropdown menu?
> ```

Yeah, retrospectively, ${} was overdoing it. Back then, I wanted a
popular pattern for variables that might be parameterizable and can't be
confused for being anything but a variable.
I briefly considered putting the variables into the "paste" context
menu, but then thought the list would get too big for small screens. But
I agree, there should be a less cumbersome way of inserting these in the
text.

> ```
>   * Add a "preview" button to the template editor so that users
>     can see a demonstration of what their template will look like.
>     Perhaps with sample data randomly selected from the user's
>     installed apps?
> ```

That's an interesting idea. The problem however is: how do you preview
mark up without knowing what the markup is? I foresee a lot of unhappy
users complaining about LMA being able to display a HTML formated list,
but not, let's say, a LaTeX one.
The only thing you could reasonably preview was if variables get
properly expanded, but then you will have users complaining that they
actually expect to see formated text and not the raw markup code.

> ```
>   * Remove redundant "You can have as many as you like" text from
>     the template editor. Users will not assume that there are any
>     limits to the number of templates.
> ```

No. Over the years, I have come to the understanding, that most users
are absolutely clueless. Have a look at the ratings of any app. You'll
find a lot of downvoting from people who did not understand the obvious.

> ```
>   * The "No apps tagged!" text may be better suited to a toast
>     notification?
> ```

Ideally yes, but as I said, most users are clueless and "No apps tagged"
is too brief of an explanation. People would not know what to do (-> bad
ratings) and you cannot really put a verbose explanation in a toast
(note: you might be able to come up with something terse in english, but
it will likely not work so well in other languages).

> I'd be interested to hear responses to any of the points above. I'm
> fully prepared to submit code for some/all of these points but I'd
> like to hear some feedback first and discuss how to progress.

Thanks for not trying to fix stuff without discussing it first ;).
